### ISSUE TITLE
how is the inference time

### ISSUE THREAD

**Issue by chenxinhua** [joeyearsley/efficient_densenet_tensorflow#2]
can this efficient denseNet implementation reduce inference time?

**Comment by joeyearsley** [comment]
No it can not reduce inference times. In fact reducing a densenets inference time is difficult due to all of the concatenation of layers. If you wish to reduce inference time you could freeze the graph and remove excess computation nodes (e.g gradients) and then the only way to get faster is to make a custom c++ op for the denseblocks or entire graph to save on the latency of starting a new op for every layer.
